# Generated by Django 4.2.7 on 2023-11-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keys',
        ),
        migrations.AddField(
            model_name='locker',
            name='key',
            field=models.CharField(default='default_value_here', max_length=100, unique=True),
        ),
    ]
