# Generated by Django 4.2.7 on 2023-11-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_cabinet_useractivity_delete_locker_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='user',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='cabinet_key',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
