# Generated by Django 4.2.7 on 2023-11-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_cabinet_user_cabinet_cabinet_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.useractivity'),
        ),
    ]
