# Generated by Django 4.2.7 on 2023-11-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_cabinet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='user',
        ),
    ]
