# Generated by Django 4.2.7 on 2023-11-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_cabinet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='cabinet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.cabinet'),
        ),
    ]
