# Generated by Django 4.2.7 on 2023-11-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_useractivity_user_useractivity_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.cabinet'),
        ),
    ]
